# Generated by Django 3.2.16 on 2025-01-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountСard',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_order', to='orders.order')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='discountсard',
            index=models.Index(fields=['-created'], name='orders_disc_created_cf2f77_idx'),
        ),
    ]
