# Generated by Django 3.2.16 on 2025-01-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20250111_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountсard',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
